### PR TITLE
Update Documentation.yaml

### PR DESCRIPTION
**Pull request by isaacsas**
This is just what Catalyst uses. It adds a lot of stuff for GLMakie support that probably isn't needed, however, it works quite well and allows us to preview the build by downloading the artifact before merging.

### CODE REVIEW

**Comment by isaacsas** [comment]
@vyudu your CI is failing it seems. Looks like a missing dependency. Do you really need an explicit dependency on `UnPack`?

**Comment by isaacsas** [comment]
Ahh I see. You need to add everything that you using in any test script as both an extra and as a target in the Project.toml.

**Comment by isaacsas** [comment]
(Assuming it isn't already a dep with a compat entry that is.)

**Comment by vyudu** [comment]
NTS: bump satisfiability when available

**Comment by isaacsas** [comment]
Wait, did you actually merge anything or did you remove all the PR code?

**Comment by vyudu** [comment]
Oh hmm, that's weird. It does seem like the documentation.yaml got updated correctly though?

**Comment by vyudu** [comment]
Ah, it's saying nothing changed because apparently I merged these changes into my local branch already a couple of days ago, then I merged my local main into this remote branch. I think I probably just messed up the direction of my merge for the first one.

**Comment by isaacsas** [comment]
Got it.

**Pull request merged**
